[[redirects]]
  from = "/mp3"
  to = "https://l.chickenfm.com/mobilemp3"
  status = 302
  force = true

[[redirects]]
  from = "/lizzo"
  to = "https://l.chickenfm.com/lizzoradio"
  status = 302
  force = true

[[redirects]]
  from = "/christmasmp3"
  to = "https://l.chickenfm.com/christmas"
  status = 302
  force = true