[[redirects]]
  from = "/mp3"
  to = "https://l.chickenfm.com/mobilemp3"
  status = 302
  force = true

[[redirects]]
  from = "/lizzo"
  to = "https://l.chickenfm.com/lizzoradio"
  status = 302
  force = true

[[redirects]]
  from = "/mp3stream"
  to = "https://radio.chickenfm.com/radio/8000/radio.mp3"
  status = 200
  force = true